COMP: Fix build errors due to Cxx17 incompatibilities
Fix issues such as: "CIP/Utilities/LesionSizingToolkit/itkCannyEdgeDetectionRecursiveGaussianImageFilter.h:196:47: error: ISO C++1z does not allow dynamic exception specifications"